import type { Metadata } from "next";
import localFont from "next/font/local";
// import { Inter_Tight } from "next/font/google";
import "./globals.css";
import Nav from "@/components/shared/Nav/Nav";
import Footerii from "@/components/shared/Footerii/Footerii";

const suissReg = localFont({
  src: "../../public/fonts/SuisseRegular.ttf",
  variable: "--suisseReg",
  display: "swap",
});

const VisbyCF = localFont({
  src: "../../public/fonts/VisbyCF.ttf",
  variable: "--VisbyCF",
  display: "swap",
});

const BoogyBrutPoster = localFont({
  src: "../../public/fonts/BoogyBrutPoster.woff2",
  variable: "--BoogyBrutPoster",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={`${suissReg.variable} ${VisbyCF.variable} ${BoogyBrutPoster.variable}`}
    >
      <body>
        <Nav />
        {children}
        <Footerii />
      </body>
    </html>
  );
}
